// Code generated by protoc-gen-go. DO NOT EDIT.
// source: heartbeat.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c667767fb9826a9, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c667767fb9826a9, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type RequestHeartbeat struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHeartbeat) Reset()         { *m = RequestHeartbeat{} }
func (m *RequestHeartbeat) String() string { return proto.CompactTextString(m) }
func (*RequestHeartbeat) ProtoMessage()    {}
func (*RequestHeartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c667767fb9826a9, []int{2}
}

func (m *RequestHeartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeartbeat.Unmarshal(m, b)
}
func (m *RequestHeartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeartbeat.Marshal(b, m, deterministic)
}
func (m *RequestHeartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeartbeat.Merge(m, src)
}
func (m *RequestHeartbeat) XXX_Size() int {
	return xxx_messageInfo_RequestHeartbeat.Size(m)
}
func (m *RequestHeartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeartbeat proto.InternalMessageInfo

func (m *RequestHeartbeat) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type ResponseHeartbeat struct {
	IsElderNow           bool     `protobuf:"varint,1,opt,name=isElderNow,proto3" json:"isElderNow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseHeartbeat) Reset()         { *m = ResponseHeartbeat{} }
func (m *ResponseHeartbeat) String() string { return proto.CompactTextString(m) }
func (*ResponseHeartbeat) ProtoMessage()    {}
func (*ResponseHeartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c667767fb9826a9, []int{3}
}

func (m *ResponseHeartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHeartbeat.Unmarshal(m, b)
}
func (m *ResponseHeartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHeartbeat.Marshal(b, m, deterministic)
}
func (m *ResponseHeartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeartbeat.Merge(m, src)
}
func (m *ResponseHeartbeat) XXX_Size() int {
	return xxx_messageInfo_ResponseHeartbeat.Size(m)
}
func (m *ResponseHeartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeartbeat proto.InternalMessageInfo

func (m *ResponseHeartbeat) GetIsElderNow() bool {
	if m != nil {
		return m.IsElderNow
	}
	return false
}

func init() {
	proto.RegisterType((*Empty)(nil), "twins.Empty")
	proto.RegisterType((*Request)(nil), "twins.Request")
	proto.RegisterType((*RequestHeartbeat)(nil), "twins.RequestHeartbeat")
	proto.RegisterType((*ResponseHeartbeat)(nil), "twins.ResponseHeartbeat")
}

func init() { proto.RegisterFile("heartbeat.proto", fileDescriptor_3c667767fb9826a9) }

var fileDescriptor_3c667767fb9826a9 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0x48, 0x4d, 0x2c,
	0x2a, 0x49, 0x4a, 0x4d, 0x2c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0x29, 0xcf,
	0xcc, 0x2b, 0x56, 0x62, 0xe7, 0x62, 0x75, 0xcd, 0x2d, 0x28, 0xa9, 0x54, 0xe2, 0xe4, 0x62, 0x0f,
	0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0x32, 0xe0, 0x12, 0x80, 0x32, 0x3d, 0x60, 0x9a, 0x84,
	0x64, 0xb8, 0x38, 0x4b, 0x32, 0x73, 0x53, 0x8b, 0x4b, 0x12, 0x73, 0x0b, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x98, 0x83, 0x10, 0x02, 0x4a, 0xc6, 0x5c, 0x82, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5,
	0xa9, 0x08, 0x2d, 0x72, 0x5c, 0x5c, 0x99, 0xc5, 0xae, 0x39, 0x29, 0xa9, 0x45, 0x7e, 0xf9, 0xe5,
	0x60, 0x3d, 0x1c, 0x41, 0x48, 0x22, 0x46, 0xc5, 0x5c, 0xac, 0x21, 0x20, 0x37, 0x08, 0x39, 0x70,
	0x71, 0x22, 0x74, 0x89, 0xeb, 0x81, 0x1d, 0xa6, 0x87, 0xee, 0x02, 0x29, 0x09, 0xb8, 0x04, 0x9a,
	0x45, 0x4a, 0x0c, 0x42, 0x1a, 0x5c, 0x6c, 0x6e, 0x99, 0x79, 0x99, 0xc5, 0x19, 0x42, 0x7c, 0xa8,
	0xda, 0xa5, 0x78, 0xa0, 0x7c, 0x88, 0x27, 0x19, 0x9c, 0x38, 0xa3, 0xd8, 0xf5, 0xac, 0xc1, 0x21,
	0x90, 0xc4, 0x06, 0xa6, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcf, 0xec, 0x81, 0x05, 0x1b,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TwinsClient is the client API for Twins service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TwinsClient interface {
	// elder tells little I'm alive
	Heartbeat(ctx context.Context, in *RequestHeartbeat, opts ...grpc.CallOption) (*ResponseHeartbeat, error)
	Finish(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Empty, error)
}

type twinsClient struct {
	cc *grpc.ClientConn
}

func NewTwinsClient(cc *grpc.ClientConn) TwinsClient {
	return &twinsClient{cc}
}

func (c *twinsClient) Heartbeat(ctx context.Context, in *RequestHeartbeat, opts ...grpc.CallOption) (*ResponseHeartbeat, error) {
	out := new(ResponseHeartbeat)
	err := c.cc.Invoke(ctx, "/twins.Twins/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twinsClient) Finish(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/twins.Twins/Finish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TwinsServer is the server API for Twins service.
type TwinsServer interface {
	// elder tells little I'm alive
	Heartbeat(context.Context, *RequestHeartbeat) (*ResponseHeartbeat, error)
	Finish(context.Context, *Request) (*Empty, error)
}

func RegisterTwinsServer(s *grpc.Server, srv TwinsServer) {
	s.RegisterService(&_Twins_serviceDesc, srv)
}

func _Twins_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestHeartbeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinsServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twins.Twins/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinsServer).Heartbeat(ctx, req.(*RequestHeartbeat))
	}
	return interceptor(ctx, in, info, handler)
}

func _Twins_Finish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinsServer).Finish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twins.Twins/Finish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinsServer).Finish(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Twins_serviceDesc = grpc.ServiceDesc{
	ServiceName: "twins.Twins",
	HandlerType: (*TwinsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _Twins_Heartbeat_Handler,
		},
		{
			MethodName: "Finish",
			Handler:    _Twins_Finish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "heartbeat.proto",
}
